version: "3.8"

networks:
  gv_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#Ogum2310
      - POSTGRES_DB=gestao_vagas

    networks:
      - gv_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv_network
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
      - "3000:3000"
    networks:
      - gv_network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
